### PR TITLE
fix: removeAssociation with multi instance devices

### LINKED ISSUE #637: [bug] List of current associations empty, but only in one group
**Version**

Build/Run method
- [X] Docker (k3s kubernetes)
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.4.1
Openzwave Version: 1.6.-1

**Describe the bug**
Associations empty in one channel of keyfob (Devolo MT2653) while other channels seem ok.

**To Reproduce**
1. Go to 'groups'
2. For node, select keyfob (node 2)
3. For group, select 'Group C' -> list of current associations is empty
4. For any other group -> list of current associations shows associated nodes

**Expected behavior**
I would expect to see a list of current associations.

**Additional context**
The list of associations seems to to be retrieved correctly though. From the log, a while after starting up zwave2mqtt and refreshing node 2 (my keyfob):
```
2020-07-22 10:40:29.547 Info, Node002, Sending (Send) message (Callback ID=0xa7, Expected Reply=0x04) - MultiChannelAssociationCmd_Get (Node=2): 0x01, 0x0a, 0x00, 0x13, 0x02, 0x03, 0x8e, 0x02, 0x04, 0x25, 0xa7, 0xed
2020-07-22 10:40:29.547 Info, Node002, Encrypted Flag is 0
2020-07-22 10:40:29.557 Detail, Node002,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
2020-07-22 10:40:29.557 Detail, Node002,   ZW_SEND_DATA delivered to Z-Wave stack
2020-07-22 10:40:29.721 Detail, Node002,   Received: 0x01, 0x07, 0x00, 0x13, 0xa7, 0x00, 0x00, 0x11, 0x5d
2020-07-22 10:40:29.722 Detail, Node002,   ZW_SEND_DATA Request with callback ID 0xa7 received (expected 0xa7)
2020-07-22 10:40:29.722 Info, Node002, Request RTT 173 Average Request RTT 532
2020-07-22 10:40:29.723 Detail, Node002,   Expected callbackId was received
2020-07-22 10:40:30.495 Detail, Node002,   Received: 0x01, 0x14, 0x00, 0x04, 0x00, 0x02, 0x0e, 0x8e, 0x03, 0x04, 0x0a, 0x00, 0x00, 0x0e, 0x01, 0x11, 0x01, 0x1b, 0x01, 0x0e, 0x02, 0x69
2020-07-22 10:40:30.495 Detail,
2020-07-22 10:40:30.495 Info, Node002, Response RTT 947 Average Response RTT 1056
2020-07-22 10:40:30.496 Info, Node002, Received MULTI_CHANNEL_ASSOCIATION_REPORT from node 2, group 4
2020-07-22 10:40:30.497 Info, Node002,   The group contains:
2020-07-22 10:40:30.497 Info, Node002,     Node 14 End Point 1
2020-07-22 10:40:30.498 Info, Node002,     Node 17 End Point 1
2020-07-22 10:40:30.498 Info, Node002,     Node 27 End Point 1
2020-07-22 10:40:30.498 Info, Node002,     Node 14 End Point 2
2020-07-22 10:40:30.498 Info, Node002, Querying associations for node 2 is complete.
2020-07-22 10:40:30.499 Detail, Node002,   Expected reply and command class was received
2020-07-22 10:40:30.499 Detail, Node002,   Message transaction complete
2020-07-22 10:40:30.501 Detail,
2020-07-22 10:40:30.501 Detail, Node002, Removing current message
2020-07-22 10:40:30.501 Detail,
```

But querying the associations returns an empty list:

```
2020-07-22T10:48:16.923Z z2m:App Zwave api call: getAssociations [ 2, 4 ]
2020-07-22T10:48:16.924Z z2m:Zwave Success zwave api call getAssociations []
```

While it does work fine for other channels:

```
2020-07-22T10:48:15.012Z z2m:App Zwave api call: getAssociations [ 2, 2 ]
2020-07-22T10:48:15.013Z z2m:Zwave Success zwave api call getAssociations [ 3 ]
```

Group 4 is the only group that does not show associations, even though it definitely has (the keyfob turns on lights and ozw logs show the associations are reported). Though group 4 is the only one with multiple associations. I ended up with 4 associations since I added a few while looking for why the list of current associations is empty. So it seems possible to add more associations, but I'm also unable to remove any of the associations (which might be related or a completely different problem)

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #637

### CODE REVIEW

File: src/components/ControlPanel.vue [hunk 1]
```diff
@@ -1290,17 +1290,23 @@ export default {
 
         // wait a moment before refresh to check if the node
         // has been added to the group correctly
-        setTimeout(this.getAssociations, 500)
+        setTimeout(this.getAssociations, 1000)
```
Comment (chrisns) [inline src/components/ControlPanel.vue:1293]: why a second, might this be more with bigger networks?

Comment (robertsLando) [reply src/components/ControlPanel.vue:1293]: @chrisns Yep, sometimes I have to reselect the group in order to get the associations, giving it some more time could prevent this :) Unfortunally there are no callbacks in zwave methods

Comment (chrisns) [reply src/components/ControlPanel.vue:1293]: can we poll until it reaches the desired state or just throw messaging to the user to say the change has been submitted?

Comment (robertsLando) [reply src/components/ControlPanel.vue:1293]: @chrisns Sometimes it could happen that the association call isn't added/removed, so nope we could just retry it some times, or add a refresh button to manually refresh current associations

Comment (chrisns) [reply src/components/ControlPanel.vue:1293]: sad face!
